import { GoogleSpreadsheet } from "google-spreadsheet";
import { sheetUsers, sheetData } from "./index";

const doc = new GoogleSpreadsheet(
  "1i99djYcrLQTrT3_lq1S8p8uwp_xZ10_C1RZvIKvcICg"
);

export const loadDoc = async () => {
  doc.useApiKey(process.env.GOOGLE_API_KEY);
  // await doc.useServiceAccountAuth({
  //   // env var values are copied from service account credentials generated by google
  //   // see "Authentication" section in docs for more info
  //   client_email: process.env.GOOGLE_CLIENT_EMAIL,
  //   private_key:
  //     process.env.GOOGLE_PRIVATE_KEY,
  // });

  await doc.loadInfo();
  /* Load Users */
  const sheet0 = doc.sheetsByIndex[0];
  const rows0 = await sheet0.getRows({ offset: 0, limit: sheet0.rowCount });
  sheetUsers.splice(0, sheetUsers.length);
  rows0.forEach((row0, index) => {
    sheetUsers.push({
      id: index,
      user: row0.user,
      password: row0.password,
    });
  });

  /* Load Data */
  const sheet1 = doc.sheetsByIndex[1];
  const rows1 = await sheet1.getRows({ offset: 0, limit: sheet1.rowCount });
  sheetData.splice(0, sheetData.length);
  rows1.forEach((row1) => {
    sheetData.push({
      "Journalist's Name": row1["Journalist's Name"],
      "Media Name": row1["Media Name"],
      "To pitch?": row1["To pitch?"],
      "Info:": row1["Info:"],
      "Search citations": row1["Search citations"],
    });
  });
  // tslint:disable-next-line:no-console
  console.log(sheetUsers);
  // tslint:disable-next-line:no-console
  console.log(sheetData);
};
